// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiuCnK3mz9XvzMdrrfXI2n5IeRx2TfBUw',
    appId: '1:731572356696:web:0c85c9bb4d0e5d4d222c2d',
    messagingSenderId: '731572356696',
    projectId: 'pharmate-968eb',
    authDomain: 'pharmate-968eb.firebaseapp.com',
    storageBucket: 'pharmate-968eb.appspot.com',
    measurementId: 'G-QDJED4VPE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsG1jT4W5MRxJWjO4HabUKtQBtT9JmP_E',
    appId: '1:731572356696:android:746b83ff9b199053222c2d',
    messagingSenderId: '731572356696',
    projectId: 'pharmate-968eb',
    storageBucket: 'pharmate-968eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChPWw7-cle9gmeK7wQdM2bU_8KHLXtCq0',
    appId: '1:731572356696:ios:6f9f7fe0d6166d73222c2d',
    messagingSenderId: '731572356696',
    projectId: 'pharmate-968eb',
    storageBucket: 'pharmate-968eb.appspot.com',
    iosBundleId: 'com.fff.pharmate',
  );
}
